version: '3.1'

services:
  blog_postgres_database:
    image: postgres:alpine3.20
    restart: "no"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: blog_relational_database
    networks:
      - blog_api_network
    ports:
      - 5432:5432

  blog_redis_database:
    image: redis:7.4.2-alpine
    restart: "no"
    command: ["redis-server", "--requirepass", "passwd"]
    networks:
      - blog_api_network
    ports:
      - "6379:6379"

  backend:
    restart: "no"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/.venv
    networks:
      - blog_api_network
    build:
      context: .
    command:
      - uv
      - run
      - main.py
      - run

networks:
  blog_api_network:
